version: "3.8"
services:
  dummy:
    build: ./services/dummy
    ports:
      - "50051:50051"
    networks:
      - backend

  openresty:
    build: ./openresty
    ports:
      - 80:80
    depends_on:
      - dummy
    volumes:
    - ./openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
    networks:
      - backend

  envoy:
    image: envoyproxy/envoy:v1.31-latest
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./services/dummy/dummy.pb:/services/dummy.pb
    ports:
      - "8080:8080"
    networks:
      - backend

  mongo: 
    image: mongo:6 
    ports: 
      - "27017:27017" 
    volumes: 
      - mongo-data:/data/db
networks:
  backend:
    driver: bridge

volumes: 
  mongo-data:
