# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import binance_interface_pb2 as binance__interface__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in binance_interface_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BinanceDataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetKlines = channel.unary_unary(
                '/binance_interface.BinanceData/GetKlines',
                request_serializer=binance__interface__pb2.GetKlinesRequest.SerializeToString,
                response_deserializer=binance__interface__pb2.GetKlinesResponse.FromString,
                _registered_method=True)
        self.GetSingleKline = channel.unary_unary(
                '/binance_interface.BinanceData/GetSingleKline',
                request_serializer=binance__interface__pb2.GetSingleKlineRequest.SerializeToString,
                response_deserializer=binance__interface__pb2.GetSingleKlineResponse.FromString,
                _registered_method=True)


class BinanceDataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetKlines(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSingleKline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BinanceDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetKlines': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKlines,
                    request_deserializer=binance__interface__pb2.GetKlinesRequest.FromString,
                    response_serializer=binance__interface__pb2.GetKlinesResponse.SerializeToString,
            ),
            'GetSingleKline': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSingleKline,
                    request_deserializer=binance__interface__pb2.GetSingleKlineRequest.FromString,
                    response_serializer=binance__interface__pb2.GetSingleKlineResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'binance_interface.BinanceData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('binance_interface.BinanceData', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BinanceData(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetKlines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/binance_interface.BinanceData/GetKlines',
            binance__interface__pb2.GetKlinesRequest.SerializeToString,
            binance__interface__pb2.GetKlinesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSingleKline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/binance_interface.BinanceData/GetSingleKline',
            binance__interface__pb2.GetSingleKlineRequest.SerializeToString,
            binance__interface__pb2.GetSingleKlineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
