# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: binance-interface.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'binance-interface.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x62inance-interface.proto\x12\x11\x62inance_interface\x1a\x1cgoogle/api/annotations.proto\"Z\n\x10GetKlinesRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08interval\x18\x02 \x01(\t\x12\x12\n\nstart_time\x18\x03 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x04 \x01(\x03\"=\n\x11GetKlinesResponse\x12(\n\x06klines\x18\x01 \x03(\x0b\x32\x18.binance_interface.Kline\"\xeb\x01\n\x05Kline\x12\x11\n\topen_time\x18\x01 \x01(\x03\x12\x0c\n\x04open\x18\x02 \x01(\x01\x12\x0c\n\x04high\x18\x03 \x01(\x01\x12\x0b\n\x03low\x18\x04 \x01(\x01\x12\r\n\x05\x63lose\x18\x05 \x01(\x01\x12\x0e\n\x06volume\x18\x06 \x01(\x01\x12\x12\n\nclose_time\x18\x07 \x01(\x03\x12\x1a\n\x12quote_asset_volume\x18\x08 \x01(\x01\x12\x18\n\x10number_of_trades\x18\t \x01(\x05\x12\x1d\n\x15taker_buy_base_volume\x18\n \x01(\x01\x12\x1e\n\x16taker_buy_quote_volume\x18\x0b \x01(\x01\"L\n\x15GetSingleKlineRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08interval\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"A\n\x16GetSingleKlineResponse\x12\'\n\x05kline\x18\x01 \x01(\x0b\x32\x18.binance_interface.Kline2\xcc\x01\n\x0b\x42inanceData\x12V\n\tGetKlines\x12#.binance_interface.GetKlinesRequest\x1a$.binance_interface.GetKlinesResponse\x12\x65\n\x0eGetSingleKline\x12(.binance_interface.GetSingleKlineRequest\x1a).binance_interface.GetSingleKlineResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'binance_interface_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETKLINESREQUEST']._serialized_start=76
  _globals['_GETKLINESREQUEST']._serialized_end=166
  _globals['_GETKLINESRESPONSE']._serialized_start=168
  _globals['_GETKLINESRESPONSE']._serialized_end=229
  _globals['_KLINE']._serialized_start=232
  _globals['_KLINE']._serialized_end=467
  _globals['_GETSINGLEKLINEREQUEST']._serialized_start=469
  _globals['_GETSINGLEKLINEREQUEST']._serialized_end=545
  _globals['_GETSINGLEKLINERESPONSE']._serialized_start=547
  _globals['_GETSINGLEKLINERESPONSE']._serialized_end=612
  _globals['_BINANCEDATA']._serialized_start=615
  _globals['_BINANCEDATA']._serialized_end=819
# @@protoc_insertion_point(module_scope)
